[[plugins]]
  package = "/plugins/lighthouse-dev/src/"

  [plugins.inputs.thresholds]
    performance = 0.9

  [[plugins.inputs.audits]]
    path = ""

  [[plugins.inputs.audits]]
    path = "contact"
